### ISSUE TITLE
ModuleNotFoundError: No module named 'autopilot'

### ISSUE THREAD

**Issue by ZHQ-air** [Karthik-Ragunath/carla_sac#6]
Thank you very much for your sharing. 
However, when I running the code from the script of carla_ppo_train.py, the following error exists.

 from autopilot.environment.carla import CarlaEnvironment
ModuleNotFoundError: No module named 'autopilot'

**Comment by ZHQ-air** [comment]
Thank you very much for your answers in advance.

**Comment by Karthik-Ragunath** [comment]
hey @ZHQ-air, we have still not opened sourced the part where we have created a wrapper around Carla.

So basically to make it work on your end, you can launch a carla server in port no, say 2021, write a gym wrapper where there will be reset and step functions which also apply controls to carla server.

**Comment by ZHQ-air** [comment]
ok, I know, thank you
